[tool.portray]
modules = ["dcm2bids"]
docs_dir = "docs"
extra_dirs = ["docs_helper/assets"]
live_reload = true
# Set plugins
[[tool.portray.extra_markdown_extensions]]
    [tool.portray.extra_markdown_extensions.toc]
    permalink = "⚓︎"
    separator = "-"

[[tool.portray.extra_markdown_extensions]]
    [tool.portray.extra_markdown_extensions."pymdownx.highlight"]
    linenums = true

[[tool.portray.extra_markdown_extensions]]
    [tool.portray.extra_markdown_extensions."pymdownx.tasklist"]
    custom_checkbox = true
    clickable_checkbox = true

[tool.portray.mkdocs]
# Repository
repo_name = "UNFmontreal/dcm2bids" # Name in top right corner
# Set repo_url so anyone running from their own repo can see the dcm2bids repo.
repo_url = "https://github.com/UNFmontreal/Dcm2Bids"
edit_uri = "blob/master/" # Bring to the page on GH, but it won't open the _edit_ mode.

# Left navigation menu
# `index` is a special case for which the parent section will be clickable and
#  link to the index.md without appending the url
nav = [{  Home = "README.md"},
        {  "Get started"    =  [{index = "docs/get-started/index.md"},
                                {"Installation" = "docs/get-started/install.md"}]},
        {   "Tutorials"     =   [{index = "docs/tutorial/index.md"},
                                {"First steps" = "docs/tutorial/first-steps.md"}]},
        {   "How-to guides" =   [{index = "docs/how-to/index.md"},
                                {"Get help and support" = "docs/how-to/get-help.md"},
                                {"Use main commands" = "docs/how-to/use-main-commands.md"},
                                {"Create a config file" =   "docs/how-to/create-config-file.md"},
                                {"Use advanced commands" = "docs/how-to/use-advanced-commands.md"},
                                {"Contribute to dcm2bids"  = "CONTRIBUTING.md"}]},
        {"Code of conduct"  =   "CODE_OF_CONDUCT.md" },
        {"Changelog"        =   "CHANGELOG.md"}
        ]

extra_css = ["docs/assets/extra.css"] # To fix some colors in light vs slate mode.

# Refer to https://squidfunk.github.io/mkdocs-material/reference/
# for the full list of extensions and config.
markdown_extensions = [ "admonition",
                        "attr_list",
                        "md_in_html",
                        "pymdownx.extra", # combines a bunch together
                        "pymdownx.caret",
                        "pymdownx.emoji",
                        "pymdownx.mark",
                        "pymdownx.tilde",
                        "pymdownx.critic",
                        "pymdownx.keys",
                        "pymdownx.details",
                        "pymdownx.tabbed",
                        "pymdownx.snippets",
                        "pymdownx.inlinehilite"]

[tool.portray.mkdocs.theme]
name = "material"
custom_dir = "docs_helper/templates" # dir to put overriding templates
features = [
            # "navigation.tabs", # moves parent categories into horizontal menu under search bar
            "navigation.indexes", # enables parents section to become and display index.md from their respective directories.
            "navigation.top" # show the "back to top" button
            ]
# Blurb that is output when the doc site is shared on social media or elsewhere.
site_description = """
  This is the documentation for dcm2bids, a community-centered project
  that aims to be an easy-to-use tool to automate the process of 1- converting
  DICOM files to NIfTI files with dcm2niix and 2- reorganising NIfTI files into the Brain
  Imaging Data Structure (BIDS).
  """

icon = {repo = "fontawesome/brands/github"} # icon in top-right corner.
# TODO: Design a logo and/or favicon.
# favicon = "art/logo_small.png"
# logo = "art/logo_small.png"

# Light vs slate mode + switch
[[tool.portray.mkdocs.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"

  [tool.portray.mkdocs.theme.palette.toggle]
  icon = "material/weather-night"
  name = "Switch to dark mode"

[[tool.portray.mkdocs.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"

  [tool.portray.mkdocs.theme.palette.toggle]
  icon = "material/weather-sunny"
  name = "Switch to light mode"

## Footer icon in bottom-right corner
[[tool.portray.mkdocs.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/UNFmontreal/Dcm2Bids"
name = "dcm2bids on GitHub"

[[tool.portray.mkdocs.extra.social]]
icon = "fontawesome/brands/docker"
link = "https://hub.docker.com/r/unfmontreal/dcm2bids"
name = "dcm2bids on docker"


# Additional plugins
[[tool.portray.mkdocs.plugins]]
[tool.portray.mkdocs.plugins.search]

[[tool.portray.mkdocs.plugins]]
[tool.portray.mkdocs.plugins.git-revision-date-localized]
type = "timeago"
# enable_creation_date = true
fallback_to_build_date = true
# [[tool.portray.mkdocs.plugins]]
# [tool.portray.mkdocs.plugins.git-authors]
