#!/usr/bin/env python
# -*- coding: utf-8 -*-


import argparse
import sys


def get_arguments():
    parser = argparse.ArgumentParser(
            formatter_class=argparse.RawDescriptionHelpFormatter,
            description="""
            """,
            epilog="""

            Not Implemented

            """)

    '''
    parser.add_argument(
            "yaml", required=True, nargs='?',
            help="YAML file describing your dicom",
            )
    '''

    args = parser.parse_args()
    return args


def main():
    """Let's go"""
    args = get_arguments()

    #print args
    #cmd = "dcm2bids -o {} -d {} -p {}".format
    #print cmd

    return 0


if __name__ == '__main__':
    sys.exit(main())
