#!/usr/bin/env python
# -*- coding: utf-8 -*-


import argparse
import os
import sys
from dcm2bids.dcm2niix import Dcm2niix


def get_arguments():
    parser = argparse.ArgumentParser(
            formatter_class=argparse.RawDescriptionHelpFormatter,
            description="",
            epilog="""
            Documentation at https://github.com/cbedetti/Dcm2Bids
            """)

    parser.add_argument(
            "-d", "--dicom_dir",
            required=True,
            nargs="+",
            help="DICOM files directory",
            )

    parser.add_argument(
            "-o", "--output_dir",
            required=False, default=os.getcwd(),
            help="Output BIDS directory, Default: current directory",
            )

    args = parser.parse_args()
    return args


def main():
    """Let's go"""
    args = get_arguments()
    app = Dcm2niix(
            dicom_dir=args.dicom_dir,
            bids_dir=args.output_dir,
            logger=False,
            )
    rsl = app.run()
    print("Example in:")
    print(os.path.join(args.output_dir, "tmp_dcm2bids", "helper"))
    return rsl


if __name__ == '__main__':
    sys.exit(main())
