#!/usr/bin/env python
# -*- coding: utf-8 -*-


import argparse
import datetime
import os
import sys
from dcm2bids.utils import save_json, make_directory_tree, write_txt
from future.utils import iteritems


def get_arguments():
    parser = argparse.ArgumentParser(
            formatter_class=argparse.RawDescriptionHelpFormatter,
            description="",
            epilog="""
            Documentation at https://github.com/cbedetti/Dcm2Bids
            """)

    parser.add_argument(
            "-o", "--output_dir",
            required=False, default=os.getcwd(),
            help="Output BIDS directory, Default: current directory",
            )

    args = parser.parse_args()
    return args


JSON_FILES = {
    "dataset_description.json": {
        "Name": "",
        "BIDSVersion": "1.0.1",
        "License": "",
        "Authors": [""],
        "Acknowledgments": "",
        "HowToAcknowledge": "",
        "Funding": "",
        "ReferencesAndLinks": [""],
        "DatasetDOI": ""
        },
    }

TEXT_FILES = {
    "README": [],
    "CHANGES": [
        "Revision history for BIDS dataset",
        "",
        "0.1 " + datetime.date.today().strftime("%Y-%m-%d"),
        "",
        " - Initialised study directory"
        ],
    }


def main():
    """Let's go"""
    args = get_arguments()

    make_directory_tree(os.path.join(args.output_dir, "derivatives"))

    for filename, data in iteritems(JSON_FILES):
        filepath = os.path.join(args.output_dir, filename)
        if not os.path.exists(filepath):
            save_json(filepath, data)

    for filename, data in iteritems(TEXT_FILES):
        filepath = os.path.join(args.output_dir, filename)
        if not os.path.exists(filepath):
            write_txt(filepath, data)

    return


if __name__ == '__main__':
    sys.exit(main())
